### ISSUE TITLE
Autoprefixer is not working?

### ISSUE THREAD

**Issue by SafaElmali** [sindresorhus/gulp-autoprefixer#112]
I am trying to use autoprefixer but I think it doesn't work.

Here my sass file
```scss
.testing {
    display: flex;
    width: percentage(5/7);
}
````

Here is my gulp task
```js
//Gulp Sass to CSS
gulp.task('sass', async function() {
    gulp.src('app/scss/styles.scss') 
        .pipe(sass()) 
        .pipe(autoprefixer()) 
        .pipe(gulp.dest('app/css'))
});
```
Output of CSS file
```css
.testing {
  display: flex;
  width: 71.42857%; }
```
Shouldn't it be like the below?

```css
.testing {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  width: 71.42857%; 
}
```
