### ISSUE TITLE
-ms prefix not added to transform

### ISSUE THREAD

**Issue by renestalder** [sindresorhus/gulp-autoprefixer#14]
As in my test, using autoprefixer with the following settings, it seems not to generate the transform attributes with the -ms prefix.

```
autoprefixer('last 2 version', 'safari 5', 'ie 9', 'opera 12.1', 'ios 6', 'android 4')
```

Raw code:

``` css
.tile__front {
  transform: rotateY(180deg);
}
```

What autoprefixer outputs

``` css
.tile__front {
  -webkit-transform: rotateY(180deg);
  transform: rotateY(180deg);
}
```

According to [caniuse](http://caniuse.com/#search=transform), the -ms prefix is needed for IE9.
