### ISSUE TITLE
linear-gradient and browser query for Safari 6 does not generate prefixed CSS

### ISSUE THREAD

**Issue by anilnatha** [sindresorhus/gulp-autoprefixer#36]
Based on information on the [caniuse.com]() site for the [linear-gradient](http://caniuse.com/#search=linear-gradient) CSS property, the CSS property should be prefixed for Safari 6.1 and earlier (with partial support for Safari 4.3 and earlier).

The following autoprefixer setup:
```javascript
.pipe($.autoprefixer({browsers: ['Explorer > 10','Firefox > 25', 'Safari > 6']}))
```
applied to the following CSS:
```css
.navBar {
	background: linear-gradient(to right, #ba0c2f 0, #410706 100%);
};
```
generates the following CSS, which _should_ include a webkit prefix, but it does not.
```css
.navBar {
  background: linear-gradient(to right, #ba0c2f 0, #410706 100%);
}
```

If I alter the autoprefixer setup to be:
```javascript
.pipe($.autoprefixer({browsers: ['Explorer > 10','Firefox > 25', 'Safari > 5']}))
```
the css appears to be prefixed as it should be:
```css
.navBar {
  background: -webkit-linear-gradient(left, #ba0c2f 0, #410706 100%);
  background: linear-gradient(to right, #ba0c2f 0, #410706 100%);
}
```
